### PR TITLE
timers: Replace timerfd_create() with POSIX api

### PR DESCRIPTION
**Pull request by sebastianlipponer**
The current timer implementation relies on `timerfd_create()` which is only available under Linux. Hence, using this DLT implementation on a POSIX compliant operating system other than Linux results in broken timers.

This change fixes this problem using a timer implementation based on `clock_gettime()`.

### CODE REVIEW

**Comment by ssugiura** [comment]
@sebastianlipponer I'm very sorry that I could not update for long time. Actually I wanted to do some performance measurement since we also have a modification locally for the same feature. As soon as the measurement is done, I will update. Thank you for your patience.

**Comment by sebastianlipponer** [comment]
@ssugiura Thanks for your feedback. How did you replace timerfd?

**Comment by ssugiura** [comment]
@sebastianlipponer We created a new thread and notify to main thread via unamed pipes so that the implementation would follow very similar to timerfd implementation.

**Comment by ssugiura** [comment]
@sebastianlipponer 
Sorry that it took so long to verify. Finally I pushed our solution into devel branch (not in master yet). Could you check if this is also fine?
https://github.com/GENIVI/dlt-daemon/pull/279/commits/53a495ffdb3cda5dc8d6d143fd0e89b0d00816c4

**Comment by sebastianlipponer** [comment]
@ssugiura Thanks for your feedback. Do you know whether the new implementation is known to work also with Green Hills Integrity?

**Comment by ssugiura** [comment]
@sebastianlipponer Unfortunately we've never tried on GHS

**Comment by sebastianlipponer** [comment]
@ssugiura I don't know when I will be able to test this. If you tested on QNX then I suggest to merge it.

**Pull request closed without merging**
