### PR TITLE
Made writev reliable for fixing data corruption

### PR DESCRIPTION
**Pull request by KalyaniPeddireddygari**
Initialized dlt_is_file_check variable which is being used at writev reliable function.

### CODE REVIEW

**Comment by sherkenhoff** [comment]
@KalyaniPeddireddygari it seems you wanted to add this commit to #123?

**Comment by KalyaniPeddireddygari** [comment]
@sherkenhoff  Yes, the commit was intended to #123. We created multiple commits due to ignorance, will make sure to create a single commit for future updates.

**Comment by gunnarx** [comment]
Personally (note I am not the maintainer, only overseeing all github.com/GENIVI) I also like that PRs are prepared with the final result and updated to show exactly what will be merged.

But a few  maintainers prefer that comments made to the PR are added as separate commits, so they see the changes.   And then **after** it was reviewed and everyone agrees, the history could be cleaned up.  In this case it is a mix of things people asked for, plus your original changes.

@sherkenhoff wrote:
>  I.e. there is no need to add a new commit to remove a trailing white space. This just unnecessarily pollutes the main branch.

Yes, it does, if it is merged in that state to the main branch.  But as you did, you can ask it to be squashed first (or do that when merging, but it's better that the submitter does it)

Sometimes submitters needs some help in how to do it.  @KalyaniPeddireddygari most repositories are set up so that you can force-push to your PR source branch and it will be updated.  So you could squash your changes together into one and force-push it, as long as this is what the maintainers ask for. 

Here you created a new PR -- probably just need a bit more knowledge of how to do things and what is possible.

To comment on this specific change proposal -  it looks interesting -- but since you completely changed when refactoring and creating the separate function, I agree it will be much easier to review if you squash all changes together into one and force-push that to #123.   If you don't know how -- ask!

**Comment by KalyaniPeddireddygari** [comment]
@gunnarx : We were not able to fetch or pull the changes submitted in the pull request 123.
Googled the stuff to squash the multiple commits to single commit but was not able to fetch the changes submitted.
Could you please let us know the steps to be followed for fetching the changes committed by us.

**Comment by gunnarx** [comment]
Fetching?  According to #123, this PR comes from your repository and the branch named "patch-1", then two other branches, "patch-2" and "patch-3".  So surely you must have the changes locally.

Anyway, I can give you the steps to combine them locally and then push the result.
First, please tell me the output of this command so I know what to call things in the commands:

```
git remote -v
```

**Comment by gunnarx** [comment]
Here are lots of example steps for combining your commits.  
**Please don't run them yet** (I will edit the message depending on what your remotes are named).

According to #123, this PR comes from your repository and the branch named "patch-1"
Then, #124 comes from another branch "patch-2" and #125 comes from "patch-4"

#123 (patch-1) adds 4 commits on top of GENIVI/master
#124 (patch-2) adds 1, also on top of GENIVI/master and not on top of #123 (patch-1) !
#125 (patch-4) adds 1, also on top of GENIVI/master and not on top of #123 (patch-1) !

Assuming you want all those changes you could do:

```
git checkout -b combined   <- let's work on a new branch
git reset patch-1          <- make the new "combined" branch start at patch-1
git cherry-pick patch-2    <- picks 1 commit from that branch, because there is only one of interest
git cherry-pick patch-4    <- same, pick one
```

You should now have 4+1+1 commits on top of master.  (I mean genivi/master, I cannot know if your local master is different)

If we assume GENIVI/master remote is named "genivi" in your copy.  If your remote "origin" instead points to the GENIVI URL then replace genivi with origin:
Continuing on the above:

```
git fetch genivi        (or origin...)
```
check what you have:
```
git log --decorate --oneline combined --not genivi/master
```
This should list 6 commits (with some branch/tags shown also) that exist on your combined branch, but do not exist in GENIVI/master

Now squash them together
```
git rebase -i HEAD~6     <-  Interactive rebase starting 6 steps behind HEAD
```
actually the following should mean the same thing and we don't need to know how many commits to process: do:
```
git rebase -i genivi/master     <-  Interactive rebase starting at master
```
- Now in the editor change "pick" to "s"   (it means squash) for every line except the first one.
- Save buffer.
- A new editor appears for the commit message.  Make one combined and good quality commit message.
Save and exit editor.

Now check again:
```
git log --decorate --oneline combined --not origin/master
```
There shold now be only one (combined) commit above master.  View the result with 
``` 
git diff HEAD^ HEAD
```

To update the original PR:
```
git checkout patch-1
git reset combined  <- change patch-1 to point to combined (we want to use patch-1 branch because that defines PR #123 and this cannot be changed.  In that case you need a new PR .
git push -f    <- force push (update) the patch-1 in your own GitHub copy, which also means the PR updates.
```
alternatively, push a new PR and close the others

**Comment by KalyaniPeddireddygari** [comment]
@gunnarx 
Below is the output  for the command "git remote -v"
origin	https://github.com/GENIVI/dlt-daemon.git (fetch)
origin	https://github.com/GENIVI/dlt-daemon.git (push)

**Comment by gunnarx** [comment]
OK. It is strange to not have a remote pointing to your own copy of the repository on github.com/KalyaniPeddireddygari   but I added that command and adjusted the commands above.

Hope this helps a bit even if it lookas advanced.  But it sounds like you might need to get some training for git, a git tutorial or similar, so you don't end up in this situation again.  Once you pushed the combined result to #123, the other PRs can be closed and the maintainer can review your combined results (maybe with a few more things to change.  If those are smaller fixes make those changes by

1. Check out the kalyani/patch-1 (that PR is defined by)
2. Make changes
3. Git add changed files
4. 
``` 
git commit --amend
```
This will squash the changes into the same commit.  
5. Then you force-push the result got patch-1 again

**Comment by gunnarx** [comment]
(And if this also fails, we might ask someone else to clean up the git history and combine your changes for you, and for you to go and learn more git ;-)

**Comment by gunnarx** [comment]
Also note, even if we worked on it a lot now, it is not certain that the behavior change you propose is acceptable to the maintainers of course.  We will know when it is in a better state.

**Comment by KalyaniPeddireddygari** [comment]
@gunnarx  

> Here are lots of example steps for combining your commits.
> 
> NEWS: Apparently you have no remote for your copy of the repo (https://github.com/KalyaniPeddireddygari/dlt-daemon)?? How did you upload the patch-1 branches in the first place? Maybe you provided the address directly. Maybe you also re-cloned the repository and therefore lost your changes. I don't know, it's a bit confusing. Anyway, let's use a remote:
> 
> Adding remote:
> 
> ```
> git remote add kalyani  https://github.com/KalyaniPeddireddygari/dlt-daemon
> ```
> 
> According to #123, this PR comes from your repository and the branch named "patch-1"
> Then, #124 comes from another branch "patch-2" and #125 comes from "patch-4"
> 
> #123 (patch-1) adds 4 commits on top of GENIVI/master
> #124 (patch-2) adds 1, also on top of GENIVI/master and not on top of #123 (patch-1) !
> #125 (patch-4) adds 1, also on top of GENIVI/master and not on top of #123 (patch-1) !
> 
> Assuming you want all those changes you could do:
> 
> ```
> git checkout -b combined   # <- let's work on a new branch
> git fetch kalyani                  # <- just in case you for some reason don't have your own changes!?
> git reset kalyani/patch-1         # <- make the new "combined" branch start at patch-1
> git cherry-pick kalyani/patch-2    # <- picks 1 commit from that branch, because there is only one of interest
> git cherry-pick kalyani/patch-4    # <- same, pick one
> ```
> 
> You should now have 4+1+1 commits on top of master. (I mean GENIVI master, I cannot know if your local master is different)
> 
> If we assume GENIVI/master remote is named "origin" in your copy, as you said it was:
> 
> ```
> git fetch origin      # <- origin must point to GENIVI copy, as you indicated
> ```
> 
> check what you have:
> 
> ```
> git log --decorate --oneline combined --not origin/master
> ```
> 
> This should list 6 commits (with some branch/tags shown also) that exist on your combined branch, but do not exist in GENIVI/master
> 
> Now squash them together
> 
> ```
> git rebase -i HEAD~6     # <-  Interactive rebase starting 6 steps behind HEAD
> ```
> 
> or alternatively, the following line would mean the same thing and we don't need to know how many commits to process:
> 
> ```
> git rebase -i origin/master     # <-  Interactive rebase starting at upstream master
> ```
> 
> * Now in the editor change "pick" to "s"   (it means squash) for every line **except** the first one.
> * This will squash every change into the previous
> * Save buffer.
> * A new editor appears for the commit message.  Make one combined and good quality commit message.
>   Save and exit editor.
> 
> Now check again:
> 
> ```
> git log --decorate --oneline combined --not origin/master
> ```
> 
> There should now be only one (combined) commit above master.
> 
> View the combined result with
> 
> ```
> git diff HEAD^ HEAD
> ```
> 
> Here, since I just can't understand your setup I cannot be sure you actually have the "patch-1" branch locally. But we will just push from combined to kalyani/patch-1, which we all can see exists on GitHub at least. That is also the base of the PR so the PR will be updated when you force-push it.
> 
> To update #123:
> 
> ```
> git checkout combined    <-  We should be here already, but just in case
> git push -f kalyani combined:patch-1   <- force push this branch, combined, but call it patch-1 in the destination
> ```
> 
> Since remote kalyani has a https address, you will need to authenticate to GitHub with username and password.

It worked! Thanks a lot for your help!

**Comment by KalyaniPeddireddygari** [comment]
@gunnarx  #123 i.e patch-1 is been updated with #124 & #125. Could you please let us know how can we delete/remove the other two PR's(#124 & #125).

**Comment by gunnarx** [comment]
@KalyaniPeddireddygari You can just select "Close" on the Pull Request, can't you?  In any case it's more a question for the maintainer, which is not me.  I just jumped in to help you clean up.  
@ssugiura is the maintainer (supported by @sherkenhoff it seems) for this project.  Thanks.

**Comment by KalyaniPeddireddygari** [comment]
Merged the changes to #123 PR

**Pull request closed without merging**
